### ISSUE TITLE
platform bug

### ISSUE THREAD

**Issue by androidwoman** [ChampionsGoal/browser_image_compression#1]
hey 
Thank you for the excellent library

There is a problem
You used html and js packages and this causes problems in running the application on other platforms

For example, I tried to run the example on Windows and it got many errors

**Comment by rsegecin** [comment]
hi @androidwoman, this package is intended only to be used for web. I think I made it very clear on Readme and on the packages pub.dev page.

**Comment by rsegecin** [comment]
hi @androidwoman, 

I’m truly sorry for my previous response. I realize now that I didn’t fully grasp the issue you were experiencing and that my reply was not helpful. I regret any frustration this may have caused.

I’ve revisited the problem and believe I’ve found a solution that addresses the issue more accurately. I hope this resolves the problem you were facing.
