### ISSUE TITLE
It seems file name must valid?

### ISSUE THREAD

**Issue by davidCcD** [ChampionsGoal/browser_image_compression#2]
Hi, I use your browser_image_compression to compress Uint8List, but failed. Before image compression, I need to crop the image, therefore I have no file name for BrowserImageCompression.compressImage(), I just write 'a.jpg' as file name while the Uint8List is correct Uint8List. And the result is failed with errors: 

TypeError: dart.global.imageCompression is not a function
packages/browser_image_compression/browser_image_compression.dart 121:35  compressImage
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54        runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5        _async
packages/browser_image_compression/browser_image_compression.dart 110:41  compressImage

So, the file name must valid? How can I compress a Uint8List after crop, without file name?

**Comment by rsegecin** [comment]
I think the way you did should work as well, the error seems that you're missing to add the javascript library in the header of the index.html (see readme.md) or for some other reason js.dart is not being able to bridge the gap between dart and JS. Were you able to compress an image without cropping?

**Comment by davidCcD** [comment]
hi, @rsegecin, surely I have the code in index.html (<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/browser-image-compression@2.0.2/dist/browser-image-compression.js"></script>). And I tried to compress an image without cropping as you said, the result is the same. Here is my code:

image_crop_compress_upload.dart:
`class ImageCropCompressUpload extends StatefulWidget {
  final String title;
  final List<XFile> pickedFiles;

  const ImageCropCompressUpload({
    Key? key,
    required this.title,
    required this.pickedFiles,
  }) : super(key: key);

  Future<void> _cropImage() async {
    String msg = '';
    try {
      int fileLength = await widget.pickedFiles[0].length();
      debugPrint('select image file: ${widget.pickedFiles[0].name}, length: $fileLength');
      fileData = await widget.pickedFiles[0].readAsBytes();
          if (context.mounted) {
            await AppUtil.compressJpgWeb(context, widget.pickedFiles[0].name,
                    fileData!, _mimeType, 3.0, _finalWidth, _finalHeight)
                .then((value) { // <- image_crop_compress_upload.dart 262
              if (value != null) {
                _uploadImage(value);
              }
            });
          }
    } catch (e, stack) {
      msg = 'failed: $e\n $stack';
      debugPrint(msg);
      setState(() {
        _cropping = false;
      });
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          backgroundColor: Colors.redAccent,
          content: Text('error. $msg'),
        ),
      );
    }
    debugPrint(msg);
  }
`
And, my app_util.dart:
`class AppUtil {
import 'package:image/image.dart' as img;
import 'package:browser_image_compression/browser_image_compression.dart';

static Future<Uint8List?> compressJpgWeb( // <- app_util.dart 1133
      BuildContext context, String fileName, Uint8List list, String mimeType, double maxSizeMB, double maxWidth, double maxHeight,
      {bool keepRatio = false}) async {
    final _imageNotifier = ValueNotifier<Uint8List?>(null);
    final _progressIndicatorNotifier = ValueNotifier<double?>(null);

    Uint8List? afterCompress;

    img.Image imageAfterCrop = img.decodeImage(list)!;
    debugPrint(
        'current width: ${imageAfterCrop.width}, height: ${imageAfterCrop.height}');

    Size targetSize = AppUtil.getCompressionSize(
        imageAfterCrop.width.toDouble(),
        imageAfterCrop.height.toDouble(),
        maxWidth,
        maxHeight,
        keepRatio: keepRatio);
    int minWidth = targetSize.width.floor();
    int minHeight = targetSize.height.floor();
    debugPrint('target width: $minWidth, height: $minHeight');
    double maxWidthOrHeight = math.min(minWidth, minHeight).toDouble();
      debugPrint('is list null? ${list == null}');
      _imageNotifier.value = await BrowserImageCompression.compressImage(
        fileName,
        list,
        mimeType,
        Options(
          maxSizeMB: maxSizeMB,
          maxWidthOrHeight: maxWidthOrHeight,
          useWebWorker: true,
          onProgress: (progress) {
            _progressIndicatorNotifier.value = progress;  // <- app_util.dart 1171
            debugPrint("progress: $progress");
          },
        ),
      );

      _progressIndicatorNotifier.value = null;

      if (_imageNotifier.value != null) {
        final finalSize = (_imageNotifier.value!).length;
        afterCompress = _imageNotifier.value;
      }
    return afterCompress;
  }

}`

And the output messages:

select image file: 02-singapore.jpg, length: 474253
current width: 1200, height: 1197
target width: 200, height: 200
is list null? false
failed: NoSuchMethodError: tried to call a non-function, such as null: 'dart.global.imageCompression'
 packages/browser_image_compression/**browser_image_compression.dart 121**:35          compressImage
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/browser_image_compression/**browser_image_compression.dart 110**:41          compressImage
packages/admin/utils/**app_util.dart 1171**:56                                        compressJpgWeb
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                _async
packages/admin/utils/**app_util.dart 1133**:43                                        compressJpgWeb
packages/admin/views/**image_crop_compress_upload.dart 262**:35                       _cropImage
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 784:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 813:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 575:7                                         [_complete]
dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
dart-sdk/lib/async/stream.dart 1581:7                                             <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39  dcall
dart-sdk/lib/html/dart2js/html_dart2js.dart 37263:58                              <fn>

**Comment by rsegecin** [comment]
does the example from this lib works in your machine? what does console output from your browser prints out? have you added the browser image compressor javascript CDN before or after `<script src="flutter.js" defer></script>`? try adding it before if not.

**Comment by davidCcD** [comment]
> does the example from this lib works in your machine? what does console output from your browser prints out? have you added the browser image compressor javascript CDN before or after `<script src="flutter.js" defer></script>`? try adding it before if not.

Yes, finally I success by edit the index.html. I copy all codes including <script src="flutter.js" defer></script> from the example to my index.html, then tried times (It seems Hot Reload is not works, maybe need Hot Restart or Rebuild), the compression is working in my project now, either without crop or after crop (I provide a fake fileName as '1.jpg' while Uint8List and mimeType is real and correct).

Thank you, @rsegecin , you noticed me that index.html have other codes need to add, which ReadMe.md hasn't mention. Maybe newbies like me don't know. I closed this issue and wish other newbies who meet alike problem will notice how to solve it by follow rsgecin said above.

**Comment by davidCcD** [comment]
Hi, @rsegecin , it's me again :-)

After add <script src="flutter.js" defer></script> to my index.html, compression works fine -- but not every time. Sometimes, still will fail with error: TypeError: dart.global.imageCompression is not a function.

It seems error is caused by missing flutter.js or browser-image-compression.js?
But how can I know these js files are downloaded or not, and do no execute compression code before downloaded?
Can I include these js files in assets, and then how to use?

Here is error message from Chrome:

browser_image_compression.dart:121 Uncaught (in promise) TypeError: dart.global.imageCompression is not a function
    at compressImage (browser_image_compression.dart:121:35)
    at compressImage.next (<anonymous>)
    at runBody (async_patch.dart:84:54)
    at Object._async [as async] (async_patch.dart:123:5)
    at BrowserImageCompression.compressImage (browser_image_compression.dart:110:41)
    at compressJpgWeb (app_util.dart:1114:57)
    at compressJpgWeb.next (<anonymous>)
    at runBody (async_patch.dart:84:54)
    at Object._async [as async] (async_patch.dart:123:5)
    at AppUtil.compressJpgWeb (app_util.dart:1088:43)
    at select_and_web_upload.dart:213:18
    at _RootZone.runUnary (zone.dart:1661:54)
    at _FutureListener.then.handleValue (future_impl.dart:147:18)
    at handleValueCallback (future_impl.dart:784:44)
    at _Future._propagateToListeners (future_impl.dart:813:13)
    at [_completeWithValue] (future_impl.dart:584:5)
    at async._AsyncCallbackEntry.new.callback (future_impl.dart:657:7)
    at Object._microtaskLoop (schedule_microtask.dart:40:11)
    at _startMicrotaskLoop (schedule_microtask.dart:49:5)
    at async_patch.dart:177:15

**Comment by rsegecin** [comment]
`<script src="flutter.js" defer></script>` supposedly should already be there, take a look [here](https://docs.flutter.dev/platform-integration/web/initialization) to learn about flutter's `index.html`. 

As this problem is not correlated with the package itself I'm closing this issue.
