### ISSUE TITLE
dart:html Error on Non-Web Platforms Despite Web-Specific Usage

### ISSUE THREAD

**Issue by Erengun** [ChampionsGoal/browser_image_compression#3]
Hello,

I'm using the `browser_image_compression` package in my Flutter project, which targets both web and mobile platforms. I've specifically used this package for my web pages only, but I still encounter a `dart:html` error when trying to build for iOS or Android.

Here's a simplified example of how I'm using the package:

```dart
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:browser_image_compression/browser_image_compression.dart';
import 'package:image_picker/image_picker.dart';

void main() async {
  final XFile? xfile = await ImagePicker().pickImage(source: ImageSource.gallery);

  if (xfile != null && kIsWeb) {
    final initialSize = await xfile.length();

    var image = await BrowserImageCompression.compressImage(
      basename(xfile.path),
      await xfile.readAsBytes(),
      lookupMimeType(xfile.name).toString(),
      Options(
        maxSizeMB: 1,
        maxWidthOrHeight: 2048,
        useWebWorker: true,
        onProgress: (progress) {
          print('Compression progress: $progress');
        },
      ),
    );

    print('Image compressed successfully');
  } else {
    // Non-web specific code
    // ... rest of the code
  }
}
```

Despite this web-specific usage, I get the following error when building for iOS or Android:

```
Error: Dart library 'dart:html' is not available on this platform.
```

This error occurs because the `browser_image_compression` package uses the `dart:html` library, which is not available on non-web platforms. 

One potential solution could be to use the `universal_html` package instead of `dart:html`. This package provides a version of `dart:html` that can be used on all platforms. You could then add platform checks in your code and throw an exception if the platform is not web. This way, the package could be compiled on mobile platforms but still only used on the web.

Is there a workaround for this issue, or could there be a future update to the package that makes it compatible with non-web platforms? Any guidance would be greatly appreciated.

Thank you for your time and assistance.

**Comment by rsegecin** [comment]
Thank you for the contribution. I've just added it to a new version of the package.

**Comment by rsegecin** [comment]
I'm sorry, I didn't bother trying to compile this library for other platforms other than web and I see the problem now. I've changed `dart:html` to `universal_html` but `browser_image_compression` still won't compile for other platforms as you can't use `dart:js` on them. It throws an error saying:

     Error: Method not found: 'allowInterop'.
     ...
     Error: Dart library 'dart:js' is not available on this platform.

I'm opened to suggestions on how to solve it. A clue can be in [here](https://github.com/dart-lang/sdk/issues/50049) or on other packages that uses `allowInterop` and still compiles for mobile apps like [flutter_image_cropper](https://github.com/hnvn/flutter_image_cropper) their solution divides the package in different libraries, may be it's something that should be implemented here as well.

**Comment by Erengun** [comment]
You are right. In this case, the solution is to use conditional, we have to implement a platform specific implementation to use html or js in only web platforms, see for example [stackoverflow issue](https://stackoverflow.com/a/61921960)

**Comment by rsegecin** [comment]
Finally done, browser_image_compression now compiles to multiple platforms, pushing a new version soon.
